export const VIDEO_FEATURES = {
    reduceSize: "Reduce Video Size 🪶",
    trimVideo: "Trim Video ✂️",
    removeAudio: "Remove Audio 🔇",
    extractAudio: "Extract Music 🎵",
    modifySpeed: "Playback Speed 🐌",
};

export const VIDEO_FEATURES_COMMANDS = {
    reduceSize: "reducevideosize",
    trimVideo: "trimvideo",
    removeAudio: "removeaudio",
    extractAudio: "extractaudio",
    modifySpeed: "modifyspeed",
};

export const videoMimeTypes = {
    mp4: "video/mp4",
    webm: "video/webm",
    ogg: "video/ogg",
    ogv: "video/ogg",
    mov: "video/quicktime",
    avi: "video/x-msvideo",
    wmv: "video/x-ms-wmv",
    flv: "video/x-flv",
    mkv: "video/x-matroska",
    "3gp": "video/3gpp",
    "3g2": "video/3gpp2",
    m4v: "video/x-m4v",
    mpg: "video/mpeg",
    mpeg: "video/mpeg",
    mpe: "video/mpeg",
    mp2: "video/mpeg",
    m2v: "video/mpeg",
    m4p: "video/mp4",
    m4b: "video/mp4",
    m4r: "video/mp4",
    m4a: "video/mp4",
    f4v: "video/mp4",
    f4p: "video/mp4",
    f4b: "video/mp4",
    f4a: "video/mp4",
    f4r: "video/mp4",
    m2ts: "video/mp2t",
    mts: "video/mp2t",
    ts: "video/mp2t",
    vob: "video/mp2t",
    qt: "video/quicktime",
    divx: "video/divx",
};
